services:
  web:
    image: nginx
    ports:
      - 9090:80
  database:
    image: redis
  app:
    tty: true
    image: php:8.1
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    command:
      - "/bin/sh"
    entrypoint: "/bin/sh -c"
    working_dir: '/var/www/html'